### ISSUE TITLE
unable to expand struct Poker.Deck

### ISSUE THREAD

**Issue by anilmane** [mgwidmann/poker#1]
Hi Mgwidmann I tried to execut the poker game on my system but 
it shows error as follows
F:\poker>mix test
Compiling 1 file (.ex)
== Compilation error on file lib/poker/deck/server.ex ==
** (CompileError) lib/poker/deck/server.ex:14: Poker.Deck.__struct__/1 is undefined, cannot expand struct Poker.Deck
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3

can yo please guide me.

**Comment by mgwidmann** [comment]
😆 I haven't messed with this in a while... My guess is that it was previously written against an older version of Elixir...

Try removing the `__MODULE__.new()` on this line: https://github.com/mgwidmann/poker/blob/master/lib/poker/deck.ex#L29

I'm not sure if that technique works anymore as I haven't tried it in a long time...

**Comment by mgwidmann** [comment]
Ok, master is up to date and compiles now 😆

**Comment by mgwidmann** [comment]
You should know, I never really finished the actual game part 😆 ... if you want to work on it, I'd welcome any PR additions
